defaults:
  - args: args1
  - sampling: sampling1

strategy:
  # Support 'train' or 'eval' stages only
  stage_names:
    - train
    - eval

  model_names:
    - D
    - G

  train_model_names:
    - D
    - G

  eval_model_names:
    - D
    - G

  accumulate_grad:
    D: False
    G: False

  train_starts_at_epoch:
    D: 0
    G: 0
