train:
  data_provider:
    S:
      unlabeled_train_student:
        object: AugmentedGroupSampler
        num_samples: 1
        data_key: "data"
        target_key:
          - "logits"
          - "name"

      labeled_train_student:
        object: AugmentedGroupSampler
        num_samples: 1
        data_key: "data"
        target_key:
          - "target"
          - "logits"
          - "name"

      unlabeled_train_teacher:
        object: AugmentedGroupSampler
        num_samples: 1
        data_key: "data"
        target_key:
          - "logits"
          - "name"

      labeled_train_teacher:
        object: AugmentedGroupSampler
        num_samples: 1
        data_key: "data"
        target_key:
          - "target"
          - "logits"
          - "name"

eval:
  data_provider:
    S:
      unlabeled_eval_student:
        object: AugmentedGroupSampler
        num_samples: 1
        data_key: "data"
        target_key:
          - "logits"
          - "name"

      labeled_eval_student:
        object: AugmentedGroupSampler
        num_samples: 1
        data_key: "data"
        target_key:
          - "target"
          - "logits"
          - "name"
    T:
      labeled_eval_teacher:
        object: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key:
          - "target"
          - "name"
