language: python

matrix:
  include:
    - name: "Linux / Python 3.6"
      os: linux
      dist: xenial
      sudo: true
      python: 3.6

    - name: "Linux / Python 3.7"
      os: linux
      dist: xenial
      sudo: true
      python: 3.7

before_install:
  - sh ci/conda_setup.sh
  - bash $HOME/miniconda.sh -b -p $HOME/miniconda
  - export OPATH="$PATH" && export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda create -q -y -n collagen_test_env python=$TRAVIS_PYTHON_VERSION
  - conda install -y -n collagen_test_env pandoc
  - source activate collagen_test_env
  - pip install -r ci/requirements.txt
  - pip install .

script:
  - py.test tests  -v
