train:
  data_provider:
    mnist_train:
      cate: ItemLoader
      num_samples: 1
      data_key: "data"
      target_key: "data"
eval:
  data_provider:
    mnist_eval:
      cate: ItemLoader
      num_samples: 1
      data_key: "data"
      target_key: "data"
  visualizers:
    - generation
    - meters