sampling:
  train:
    data_provider:
      D:
        real:
          cate: ItemLoader
          batches_per_iter: 1
          data_key: data
          target_key: target
        fake:
          cate: FakeSampler
          batches_per_iter: 1
          data_key: data
          target_key: target
      G:
        noise:
          cate: GaussianNoiseSampler
          batches_per_iter: 1
          data_key: latent
          target_key: valid
  eval:
    data_provider:
      G:
        noise:
          cate: GaussianNoiseSampler
          batches_per_iter: 1
          data_key: latent
          target_key: valid
