train:
  data_provider:
    mymodel:
      loader_train:
        cate: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "target"
eval:
  data_provider:
    mymodel:
      loader_eval:
        cate: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "target"
