sampling:
  train:
    data_provider:
      mymodel:
        unlabeled_train:
          batches_per_iter: 1
          data_key: "mixup_data"
          target_key:
            - "logits"
            - "logits_aug"
            - "logits_mixup"
            - "alpha"
            - "name"
        labeled_train:
          batches_per_iter: 1
          data_key: "data"
          target_key:
            - "target"
            - "name"
#          batches_per_iter: 1
#          data_key: "mixup_data"
#          target_key:
#            - "logits_mixup"
#            - "target"
#            - "target_bg"
#            - "alpha"
#            - "name"

  eval:
    data_provider:
      mymodel:
        labeled_eval:
          batches_per_iter: 1
          data_key: "data"
          target_key:
            - "target"
            - "name"
