data_provider:
  train:
    D:
      real_labeled_train:
        num_samples: 1
        data_key: "data"
        target_key: "target"
      real_unlabeled_train:
        num_samples: 1
        data_key: "data"
        target_key: "target"
      fake_unlabeled_train:
        num_samples: 1
        data_key: "data"
        target_key: "target"
    G:
      fake_unlabeled_train:
        num_samples: 1
        data_key: "data"
        target_key: "target"
  eval:
    D:
      real_labeled_val:
        num_samples: 1
        data_key: "data"
        target_key: "target"
