train:
  data_provider:
    D:
      real_labeled_train:
        cate: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "target"
      real_unlabeled_train:
        cate: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "valid"
      fake_unlabeled_gen:
        cate: SSFakeSampler
        num_samples: 1
        data_key: "data"
        target_key: "valid"
    G:
      fake_unlabeled_latent:
        cate: SSFakeSampler
        num_samples: 1
        data_key: "latent"
        target_key: "valid"
  meters:
    - SSAccuracy
    - SSValidity
eval:
  data_provider:
    D:
      real_labeled_val:
        num_samples: 1
        data_key: "data"
        target_key: "target"
      real_unlabeled_val:
        object: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "valid"
      fake_unlabeled_gen:
        object: SSFakeSampler
        num_samples: 1
        data_key: "data"
        target_key: "valid"
    G:
      fake_unlabeled_latent:
        object: SSFakeSampler
        num_samples: 1
        data_key: "latent"
        target_key: "valid"
  meters:
    - SSAccuracy
    - SSValidity
  visualizers:
    - generation
    - meters
