train:
  data_provider:
    D:
      real_labeled_train:
        cate: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "target"
      real_unlabeled_train:
        cate: ItemLoader
        num_samples: 1
        data_key: "data"
        target_key: "target"
      fake_unlabeled_train:
        cate: SSFakeSampler
        num_samples: 1
        data_key: "data"
        target_key: "target"
    G:
      fake_unlabeled_train:
        cate: SSFakeSampler
        num_samples: 1
        data_key: "latent"
        target_key: "target"
  meters:
    - SSAccuracy
    - SSValidity
eval:
  data_provider:
    D:
      real_labeled_val:
        num_samples: 1
        data_key: "data"
        target_key: "target"
      fake_unlabeled_val:
        cate: SSFakeSampler
        num_samples: 1
        data_key: "data"
        target_key: "target"
    G:
      fake_unlabeled_val:
        cate: SSFakeSampler
        num_samples: 1
        data_key: "latent"
        target_key: "target"
  meters:
    - SSAccuracy
    - SSValidity
  visualizers:
    - generation
    - meters
