defaults:
  - args: args1
  - sampling: sampling1

strategy:
  # Support 'train' or 'eval' stages only
  stage_names:
    - train
    - eval

  model_names:
    - mymodel

  train_model_names:
    - mymodel

  eval_model_names:
    - mymodel

  accumulate_grad:
    mymodel: False

  train_starts_at_epoch:
    mymodel: 0
