n_epochs: 100
bs: 64
latent_size: 64
g_net_features: 32
g_lr: 1e-5
g_wd: 1e-5
d_net_features: 32
d_lr: 1e-5
d_wd: 1e-4
grid_shape: 8
g_beta: 0.5
d_beta: 0.5
dropout: 0.3
wd: 1e-4
num_threads: 4
snapshots: snapshots
seed: 12345
dataset: mnist
data_dir: ./data
log_dir: ''
comment: cnn_example
