n_epochs: 100
bs: 512
latent_size: 32
g_net_features: 64
d_net_features: 64
g_lr: 2e-4
d_lr: 2e-4
grid_shape: 8
g_beta: 0.90
d_beta: 0.90
dropout: 0.5
wd: 1e-4
num_threads: 4
snapshots: snapshots
seed: 12345
dataset: mnist
data_dir: ./data
log_dir: ''
comment: cnn_example
