sampling:
  train:
    data_provider:
      mymodel:
        loader_train:
          batches_per_iter: 1
          data_key: "data"
          target_key: "target"
  eval:
    data_provider:
      mymodel:
        loader_eval:
          batches_per_iter: 1
          data_key: "data"
          target_key: "target"
