n_epochs: 100
bs: 128
dropout: 0.5
bw: 64
wd: 1e-4
lr: 1e-4
num_workers: 4
snapshots: snapshots
seed: 12345
dataset: cifar10
data_dir: ./data
log_dir: ''
comment: cnn_example
arch_name: efficientnet-b0
alpha: 0.75